from __future__ import annotations

# Standard library imports
from datetime import date, datetime, timedelta
from decimal import Decimal
from enum import StrEnum, unique
from typing import Tuple, Union

# First-party imports
from models.exceptions.enum_exceptions import (
    MTInvalidBillingPeriodicity,
    MTInvalidWeekday,
    MTRoleNotRankable,
    MTRoutingKeyMissingCompany,
)


@unique
class RegistrationStatus(StrEnum):
    """Enumeration for the registration status of a customer.

    Attributes:
        ACTIVE (str): The customer is registered and served; their accepted
            work is planned.
        PROSPECT (str): The agency is in discussion with them. They may be
            quoted, but no visit is ever planned for them — see
            :meth:`can_be_scheduled`.
        STOPPED (str): The customer has stopped the service; no new quote or
            intervention may be created for them.

    Notes:
        **A prospect is not a lesser active customer, and not a stopped one.**
        Somebody who has been quoted but has not signed is exactly the state
        this enum had no word for: quoting them is the whole point, and routing
        an assistant to their door before they have agreed is the failure the
        third member exists to prevent.

        This is the only status a *new* customer is given. Promotion to
        :attr:`ACTIVE` is a manager's deliberate act.
    """

    ACTIVE = "active"
    PROSPECT = "prospect"
    STOPPED = "stopped"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every registration-status value.

        Returns:
            Tuple[str, ...]: ``("active", "prospect", "stopped")``.
        """
        return tuple(status.value for status in cls)

    def can_be_scheduled(self) -> bool:
        """Return whether a customer in this state may be given planned visits.

        Returns:
            bool: ``True`` only for an active customer.

        Notes:
            **The one rule the planner asks about.** A prospect may hold
            accepted, priced, perfectly routable quotes and still produce no
            requirement: the agency has not agreed to deliver the work, so
            sending somebody to the door would be the error, not the omission.

            Distinct from
            :meth:`~models.people.customer.customer.Customer.is_active` even
            though the two agree today. That one answers "what state is this
            customer in"; this one answers "may the solver place their work",
            and a later state — a customer suspended mid-contract, say — would
            separate them.
        """
        return self is RegistrationStatus.ACTIVE


@unique
class Language(StrEnum):
    """Enumeration for the language a document is written in.

    Attributes:
        FR (str): French.
        EN (str): English.

    Notes:
        - The same two codes the interface offers, so an account's stored
          preference and the language its screens are in are one value rather
          than two that can disagree.
        - French is the default everywhere, and deliberately: this is a French
          home-care agency, and a quote reaching a customer in English because
          nobody set a preference would be the wrong failure. It is a stored
          preference rather than an ``Accept-Language`` header because the
          documents are generated by the planning-completed webhook, which runs
          in the background with no browser attached to read a header from.
    """

    FR = "fr"
    EN = "en"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every language value.

        Returns:
            Tuple[str, ...]: ``("fr", "en")``.
        """
        return tuple(language.value for language in cls)


@unique
class ContractType(StrEnum):
    """Enumeration for the employment contract of a Home Care Assistant.

    Attributes:
        CDI (str): Permanent open-ended contract (contrat à durée indéterminée).
        CDD (str): Fixed-term contract (contrat à durée déterminée).
        INTERIM (str): Temporary agency contract.
        INTERNSHIP (str): Internship (stage).
    """

    CDI = "cdi"
    CDD = "cdd"
    INTERIM = "interim"
    INTERNSHIP = "internship"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every contract-type value.

        Returns:
            Tuple[str, ...]: The four supported contract types.
        """
        return tuple(contract.value for contract in cls)


@unique
class ServiceCategory(StrEnum):
    """Enumeration for the VAT category an intervention type falls under.

    Attributes:
        NECESSITY (str): Service delivered for a necessity reason, taxed at the
            reduced 5.5% VAT rate.
        COMFORT (str): Service delivered for a comfort reason, taxed at the
            standard 20% VAT rate.

    Notes:
        The category is carried by the intervention type rather than by the
        quote line: a given type of care is structurally one or the other. A
        type that would need both categories must be split into two types.
    """

    NECESSITY = "necessity"
    COMFORT = "comfort"

    def vat_rate(self) -> Decimal:
        """Return the VAT rate applicable to this category.

        Returns:
            Decimal: ``Decimal("0.055")`` for a necessity service, and
            ``Decimal("0.20")`` for a comfort service.

        Notes:
            The rate is a :class:`~decimal.Decimal` and never a float, so it
            composes with the rest of the pricing arithmetic without losing
            cents to binary floating-point representation.
        """
        rates = {
            ServiceCategory.NECESSITY: Decimal("0.055"),
            ServiceCategory.COMFORT: Decimal("0.20"),
        }
        return rates[self]

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every service-category value.

        Returns:
            Tuple[str, ...]: ``("necessity", "comfort")``.
        """
        return tuple(category.value for category in cls)


@unique
class UserRole(StrEnum):
    """Enumeration for the role granted to an authenticated account.

    Attributes:
        HCA (str): A Home Care Assistant. Declares their own availability and
            sees their own planning only.
        MANAGER (str): Sees every HCA planning, manages customers, quotes and
            the intervention-type catalog, and edits an HCA's contract type
            and certifications.
        ADMIN (str): Everything a manager can do, plus running the planning
            computation and promoting a user to manager.
        CUSTOMER (str): Somebody the agency serves, signed in to their own
            space. **Not a rung of the staff ladder** — see :meth:`rank`.
    """

    HCA = "hca"
    MANAGER = "manager"
    ADMIN = "admin"
    CUSTOMER = "customer"

    def is_staff(self) -> bool:
        """Return whether this role works for the agency.

        Returns:
            bool: ``True`` for every role but :attr:`CUSTOMER`.

        Notes:
            The one question that separates the two axes, and the only safe way
            to ask "may this account see the agency's own screens". Written as a
            method rather than repeated as ``role is not CUSTOMER`` so a fifth
            role added later cannot be admitted to the staff side by omission.
        """
        return self is not UserRole.CUSTOMER

    def rank(self) -> int:
        """Return the numeric access rank of this role.

        Returns:
            int: The access rank; a higher rank unlocks strictly more.

        Raises:
            MTRoleNotRankable: If this role is not on the staff ladder.

        Notes:
            - The ordering is shared by the whole stack so the API guards and
              any client agree on which role unlocks which feature. Rank
              comparison answers "at least a manager"; it must not be used for
              the checks that are specific to being an HCA (such as owning a
              planning), which compare the role by identity instead.
            - **:attr:`CUSTOMER` is refused rather than ranked**, and that
              refusal is the point. A customer is not above or below an
              assistant — they are a different axis. Ranked below, every
              employee would satisfy ``has_at_least(CUSTOMER)`` and a guard
              written the usual way would let staff into a household's private
              space; ranked above, a customer would satisfy the manager checks.
              There is no number that is correct, so there is no number.
        """
        ranks = {UserRole.HCA: 0, UserRole.MANAGER: 1, UserRole.ADMIN: 2}
        if self not in ranks:
            raise MTRoleNotRankable(
                f"Role {self.value!r} is not on the staff ladder and cannot be "
                f"ranked. Compare it by identity — see UserRole.is_staff."
            )
        return ranks[self]

    def has_at_least(self, minimum: UserRole) -> bool:
        """Return whether this role ranks at or above ``minimum``.

        Args:
            minimum (UserRole): The lowest role that satisfies the check.

        Returns:
            bool: ``True`` when this role's rank is greater than or equal to
            the rank of ``minimum``.

        Raises:
            MTRoleNotRankable: If either role is off the staff ladder.

        Notes:
            A customer on either side raises rather than answering. Answering
            ``False`` would be the more forgiving choice and the wrong one: the
            call is a mistake, and a mistake that returns a plausible boolean is
            one nobody finds.
        """
        return self.rank() >= minimum.rank()

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every role value.

        Returns:
            Tuple[str, ...]: ``("hca", "manager", "admin", "customer")``.
        """
        return tuple(role.value for role in cls)

    @classmethod
    def staff_values(cls) -> Tuple[str, ...]:
        """Return every role that works for the agency.

        Returns:
            Tuple[str, ...]: ``("hca", "manager", "admin")``.

        Notes:
            What a staff-facing payload validates against, so a request cannot
            promote somebody into — or out of — the customer axis by naming it.
        """
        return tuple(role.value for role in cls if role.is_staff())


@unique
class QuoteStatus(StrEnum):
    """Enumeration for the lifecycle status of a quote.

    Attributes:
        DRAFT (str): Being composed; lines may still be added or removed.
        PENDING_VALIDATION (str): Submitted by an assistant and waiting for a
            manager to validate it.
        SENT (str): Sent to the customer and awaiting their answer.
        ACCEPTED (str): Accepted by the customer. Only accepted quotes feed the
            planning computation.
        REJECTED (str): Declined by the customer.
        EXPIRED (str): Its validity date passed before an answer was given.

    Notes:
        - ``PENDING_VALIDATION`` sits between the draft and the commitment. An
          assistant knows what a customer needs but does not set the agency's
          prices, so a quote they write waits for a manager before its work is
          committed. It is deliberately a status rather than a flag: a quote is in
          exactly one place at a time, and a boolean beside the status would allow
          the nonsense of an accepted quote still awaiting validation.
        - ``SENT`` is **no longer produced by any path**. Validation used to stop
          there, needing a second acceptance that nothing on any screen asked for,
          so a validated quote's work silently never reached a planning run; both
          approval paths now end at ``ACCEPTED``. The member is kept because rows
          stored in it before that change still exist, and the interface keeps its
          tab and its accept button for exactly them.
    """

    DRAFT = "draft"
    PENDING_VALIDATION = "pending-validation"
    SENT = "sent"
    ACCEPTED = "accepted"
    REJECTED = "rejected"
    EXPIRED = "expired"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every quote-status value.

        Returns:
            Tuple[str, ...]: The six supported statuses.
        """
        return tuple(status.value for status in cls)

    def is_editable(self) -> bool:
        """Return whether the lines may still be changed.

        Returns:
            bool: ``True`` only for a draft.

        Notes:
            A quote awaiting validation is frozen: a manager must decide on the
            figures they were shown, not on figures that moved underneath them
            while they read.
        """
        return self is QuoteStatus.DRAFT

    def is_awaiting_validation(self) -> bool:
        """Return whether a manager still owes this quote a decision.

        Returns:
            bool: ``True`` when the quote sits in the validation queue.
        """
        return self is QuoteStatus.PENDING_VALIDATION


@unique
class BillingPeriodicity(StrEnum):
    """Enumeration for how often an agency invoices its customers.

    Attributes:
        WEEKLY (str): One bill per ISO week, Monday to Sunday.
        MONTHLY (str): One bill per calendar month.
        YEARLY (str): One bill per calendar year.

    Notes:
        - The member decides a **window**, and the window is the whole of what
          the specification calls a time pro-rata. A
          :class:`~models.quoting.quote_line.QuoteLine` carries one
          ``service_date``, not a range: it is a single dated visit. No line can
          therefore straddle a period boundary, and "only the part of the quote
          inside the window is billed" reduces exactly to a date filter, with no
          fractional amount computed anywhere. Lines dated after the window are
          simply absent from this bill; the next period has a different window
          and picks them up unchanged.
        - **Both bounds are inclusive**, matching every other period in the
          application: ``QuoteRepository.list_schedulable``,
          ``InterventionRepository.replace_for_period`` and
          :meth:`~models.quoting.quote.Quote.covers` all read that way. An
          exclusive end here would be the one period that behaved differently,
          and the symptom would be a day's care quietly unbilled every month.
        - Stored in the database rather than in ``app.yaml``, because the
          specification puts it in the hands of a manager and a YAML value would
          need a deployment to change. See
          :class:`~models.settings.billing_settings.BillingSettings`.
    """

    WEEKLY = "weekly"
    MONTHLY = "monthly"
    YEARLY = "yearly"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every billing-periodicity value.

        Returns:
            Tuple[str, ...]: ``("weekly", "monthly", "yearly")``.
        """
        return tuple(periodicity.value for periodicity in cls)

    def window_for(self, day: Union[date, datetime]) -> Tuple[date, date]:
        """Return the billing window that contains a day.

        Args:
            day (Union[date, datetime]): Any day inside the wanted period.

        Returns:
            Tuple[date, date]: The first and last day of the period, **both
            inclusive**.

        Raises:
            MTInvalidBillingPeriodicity: If ``day`` is not a date.

        Notes:
            - The month's last day is computed as "the first of next month,
              minus one day" rather than by asking how long the month is, so
              February and a leap year need no special case and there is one
              arithmetic path instead of twelve.
            - The week is anchored on Monday, the same anchoring
              :meth:`~service.quotes.quotes.QuoteService._monday_of` derives
              from 4 January, so a weekly bill and a weekly quote aggregate
              cover the same seven days.
        """
        if not isinstance(day, date):
            raise MTInvalidBillingPeriodicity(f"Invalid day: {day!r}. Must be a date.")
        if isinstance(day, datetime):
            day = day.date()
        if self is BillingPeriodicity.WEEKLY:
            start = day - timedelta(days=day.isoweekday() - 1)
            return start, start + timedelta(days=6)
        if self is BillingPeriodicity.MONTHLY:
            start = day.replace(day=1)
            next_month = date(day.year + day.month // 12, day.month % 12 + 1, 1)
            return start, next_month - timedelta(days=1)
        return date(day.year, 1, 1), date(day.year, 12, 31)

    def previous_window(self, day: Union[date, datetime]) -> Tuple[date, date]:
        """Return the window that ends immediately before the one holding a day.

        Args:
            day (Union[date, datetime]): Any day inside the current period.

        Returns:
            Tuple[date, date]: The previous period's first and last day.

        Raises:
            MTInvalidBillingPeriodicity: If ``day`` is not a date.

        Notes:
            "Bill last month" is what an agency actually asks for — a period is
            invoiced once it has been delivered — and the arithmetic is one day
            back from the current window's start rather than a month subtracted
            from ``day``, which would land on 28 February from 31 March. Doing
            it here stops every caller getting that wrong separately.
        """
        start, _ = self.window_for(day)
        return self.window_for(start - timedelta(days=1))


@unique
class BillStatus(StrEnum):
    """Enumeration for where a bill has reached commercially.

    Attributes:
        TO_BE_VALIDATED (str): Generated, with its document, and waiting for a
            manager to approve it. Nothing has reached the customer.
        ACCEPTED (str): Approved by a manager. Approval is what sends it.
        WAITING_PAYMENT (str): Sent to the customer; the money is outstanding.
        PAID (str): Settled.

    Notes:
        - **Only a manager or an administrator moves a bill.** The status is a
          statement about money owed, and an assistant who could set one would
          be writing the agency's accounts.
        - Two things this enumeration deliberately does **not** record: whether
          a document exists — that is ``Bill.document_key`` — and whether
          generation failed, which is
          :class:`BillingRunStatus`. Folding a generation outcome in here would
          make "waiting payment" mean two unrelated things, and a manager
          reading the list could not tell a bill nobody has paid from one nobody
          managed to produce.
        - There is no ``CANCELLED``. French invoice numbering forbids both reuse
          and gaps, so a mistaken invoice is corrected by a credit note rather
          than withdrawn — and a credit note is a document in its own right, not
          a status on this one.
    """

    TO_BE_VALIDATED = "to-be-validated"
    ACCEPTED = "accepted"
    WAITING_PAYMENT = "waiting-payment"
    PAID = "paid"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every bill-status value.

        Returns:
            Tuple[str, ...]: The four supported statuses, in the order reached.
        """
        return tuple(status.value for status in cls)

    def is_terminal(self) -> bool:
        """Return whether the bill has nothing further to reach.

        Returns:
            bool: ``True`` only for :attr:`PAID`.
        """
        return self is BillStatus.PAID

    def can_move_to(self, target: BillStatus) -> bool:
        """Return whether a manager may move a bill from here to ``target``.

        Args:
            target (BillStatus): The status being asked for.

        Returns:
            bool: ``True`` when ``target`` is the next status or the previous
            one.

        Notes:
            **One step, either way.** Forward is the lifecycle; backward is the
            correction, and a manager who marked the wrong row paid needs it —
            an irreversible status would leave them editing the database.
            Anything further is refused: a bill going straight from
            :attr:`TO_BE_VALIDATED` to :attr:`PAID` would skip the record of it
            ever having been approved, and of it ever having been sent, which is
            the audit trail the four statuses exist to keep.
        """
        order = tuple(BillStatus)
        return abs(order.index(target) - order.index(self)) == 1


@unique
class BillingRunStatus(StrEnum):
    """Enumeration for the lifecycle status of a bill-generation run.

    Attributes:
        PENDING (str): Accepted and queued, not yet picked up.
        RUNNING (str): Bills are being generated.
        SUCCEEDED (str): Every customer with billable work was billed.
        PARTIAL (str): Some customers were billed and some failed.
        FAILED (str): The run ended on an error; see the run's error message.

    Notes:
        Deliberately not :class:`PlanningRunStatus`, whose members mean
        something else: there, :attr:`PARTIAL` describes visits that could not
        be placed. Here it describes customers who could not be billed, and one
        enumeration answering to two vocabularies is how a status chip ends up
        telling somebody the wrong thing.
    """

    PENDING = "pending"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    PARTIAL = "partial"
    FAILED = "failed"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every billing-run-status value.

        Returns:
            Tuple[str, ...]: The five supported statuses.
        """
        return tuple(status.value for status in cls)

    def is_terminal(self) -> bool:
        """Return whether no further status change can follow this one.

        Returns:
            bool: ``True`` for :attr:`SUCCEEDED`, :attr:`PARTIAL` and
            :attr:`FAILED`.

        Notes:
            Clients poll a run until this returns ``True``. A partial run is
            finished — the bills that could be written are written — so a client
            that kept polling would wait forever.
        """
        return self in (
            BillingRunStatus.SUCCEEDED,
            BillingRunStatus.PARTIAL,
            BillingRunStatus.FAILED,
        )


@unique
class RecipientKind(StrEnum):
    """Enumeration for what kind of party an invoice is addressed to.

    Attributes:
        INDIVIDUAL (str): A private person — the household being cared for.
        BUSINESS (str): A company: a mutuelle, a pension fund, an employer.
        PUBLIC (str): A public body: a conseil départemental, a CCAS.

    Notes:
        - **This decides which regulatory regime the invoice falls under**, not
          merely how it is addressed. An individual means *e-reporting*: the
          transaction is declared to the tax authority and the customer receives
          whatever the agency already sends them. A business or a public body
          means *e-invoicing*: a structured document routed through a platform,
          which the recipient's own system reads. Getting the kind wrong sends
          the invoice down the wrong path entirely.
        - The two non-individual kinds are kept apart even though both are
          e-invoicing, because a public body routes by an additional service
          code and is reached through a different platform. Folding them into
          one "professional" kind would lose the only distinction that changes
          where the document goes.
        - A household has no SIREN, and that is a fact rather than missing data.
          It is why the identifier is optional on the recipient and required by
          the other two kinds — see
          :class:`~models.billing.bill_recipient.BillRecipient`.
    """

    INDIVIDUAL = "individual"
    BUSINESS = "business"
    PUBLIC = "public"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every recipient kind.

        Returns:
            Tuple[str, ...]: ``("individual", "business", "public")``.
        """
        return tuple(kind.value for kind in cls)

    def requires_legal_identifier(self) -> bool:
        """Return whether this kind of recipient must carry a SIREN.

        Returns:
            bool: ``True`` for a business or a public body.

        Notes:
            A structured invoice addressed to a professional is routed on that
            identifier, so one without it cannot be delivered at all. A private
            individual has none to give, which is why the field is optional on
            the model and this is what makes it required where it applies.
        """
        return self is not RecipientKind.INDIVIDUAL

    def requires_electronic_invoice(self) -> bool:
        """Return whether this recipient must be sent a structured invoice.

        Returns:
            bool: ``True`` for a business or a public body.

        Notes:
            The mirror of it is just as load-bearing: a ``False`` here means the
            invoice is **reported**, not transmitted, and a home-care agency's
            revenue is mostly of that kind. Asking this rather than testing
            ``kind is INDIVIDUAL`` at each call site is what keeps the reform's
            own vocabulary in the code.
        """
        return self.requires_legal_identifier()


@unique
class OperationNature(StrEnum):
    """Enumeration for what an invoice covers: goods, services, or both.

    Attributes:
        GOODS (str): A supply of goods.
        SERVICES (str): A supply of services.
        MIXED (str): Both, on one document.

    Notes:
        - A **mandatory mention** on a French invoice, and one this agency would
          otherwise never have written down: everything it sells is a service,
          so the value is constant today. It is stored rather than assumed
          because a constant that is never recorded is a constant nobody
          notices changing — the day the agency starts invoicing equipment, an
          implicit "services" would be a false declaration on every line of it.
        - It also decides when VAT falls due. On services the tax is exigible on
          **collection**, which is why a bill reaching
          :attr:`BillStatus.PAID` is a reportable event and not merely an
          accounting nicety.
    """

    GOODS = "goods"
    SERVICES = "services"
    MIXED = "mixed"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every operation nature.

        Returns:
            Tuple[str, ...]: ``("goods", "services", "mixed")``.
        """
        return tuple(nature.value for nature in cls)

    def includes_services(self) -> bool:
        """Return whether any part of the invoice is a supply of services.

        Returns:
            bool: ``True`` for services and for a mixed operation.

        Notes:
            Asked when deciding whether the collection date has to be reported.
            A mixed invoice counts, because the services on it are exigible on
            collection whatever the goods beside them do.
        """
        return self in (OperationNature.SERVICES, OperationNature.MIXED)


@unique
class EInvoicingProvider(StrEnum):
    """Enumeration for the certified platforms this application can speak to.

    Attributes:
        B2BROUTER (str): B2Brouter, a Spanish platform and Peppol access point.
        STORECOVE (str): Storecove, a Dutch API-first platform.
        INVOPOP (str): Invopop, built around the open GOBL document format.
        IOPOLE (str): Iopole, French and hosted on SecNumCloud.

    Notes:
        - **Membership of this enumeration is a claim about documentation, not
          about quality.** Of the 145 platforms holding a registration number,
          these four are the ones publishing an API a developer can integrate
          against without signing anything first. A platform absent from here is
          not disqualified — it simply cannot be written against yet.
        - Every one of them is **immatriculée sous réserve**: registered, with
          the audit report still outstanding. The status has to be re-checked
          against ``impots.gouv.fr`` before an agency contracts with one, which
          is why nothing in the code treats presence here as certification.
        - The values are stored in the database and sent to the browser, so they
          are stable identifiers rather than display names. What a card in the
          gallery is *called* belongs to
          :class:`~models.integrations.provider_descriptor.ProviderDescriptor`.
    """

    B2BROUTER = "b2brouter"
    STORECOVE = "storecove"
    INVOPOP = "invopop"
    IOPOLE = "iopole"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every provider value.

        Returns:
            Tuple[str, ...]: The four supported platforms.
        """
        return tuple(provider.value for provider in cls)


@unique
class TransmissionKind(StrEnum):
    """Enumeration for what was actually sent to a platform about an invoice.

    Attributes:
        INVOICE (str): The structured invoice itself, routed to a business.
        PAYMENT_REPORT (str): Payment data declared to the tax authority.
        CHORUS_PRO (str): The structured invoice, routed to a public body.

    Notes:
        - **These are three different obligations, not three destinations for
          one document.** An invoice to a mutuelle is *e-invoicing*: the
          recipient's own system reads it. A household's settled invoice is
          *e-reporting*: nothing reaches the customer, and what reaches the
          administration is the fact that money changed hands — flux 10.4,
          mandatory for services because VAT falls due on collection. Recording
          which of the three happened is what makes a transmission auditable
          afterwards; a single "sent" flag could not answer "sent as what?".
        - :attr:`CHORUS_PRO` is kept apart from :attr:`INVOICE` even though both
          carry a structured document, because a public body is reached through
          a different route and addressed by an additional service code. Folding
          them together would lose the only distinction that changes where the
          document goes — the same reasoning
          :class:`RecipientKind` gives for keeping its own two apart.
    """

    INVOICE = "invoice"
    PAYMENT_REPORT = "payment-report"
    CHORUS_PRO = "chorus-pro"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every transmission kind.

        Returns:
            Tuple[str, ...]: ``("invoice", "payment-report", "chorus-pro")``.
        """
        return tuple(kind.value for kind in cls)

    @classmethod
    def for_recipient(cls, kind: RecipientKind) -> TransmissionKind:
        """Return what must be transmitted for a recipient of this kind.

        Args:
            kind (RecipientKind): Who the invoice is addressed to.

        Returns:
            TransmissionKind: The obligation that applies.

        Notes:
            **The reform's routing rule, in one place.** Written here rather
            than as a branch in the transmission service so that the question
            "what happens to a public body's invoice?" has exactly one answer in
            the codebase, and so that adding a fourth kind of recipient fails
            here — loudly, at the mapping — rather than silently falling through
            to whatever the ``else`` branch happened to be.
        """
        if kind is RecipientKind.PUBLIC:
            return cls.CHORUS_PRO
        if kind is RecipientKind.BUSINESS:
            return cls.INVOICE
        return cls.PAYMENT_REPORT


@unique
class TransmissionStatus(StrEnum):
    """Enumeration for how far a transmission to a platform has reached.

    Attributes:
        PENDING (str): Queued, not yet attempted.
        SENT (str): The platform accepted it for delivery.
        FAILED (str): The attempt failed; it may be retried.

    Notes:
        - **Deliberately not a mirror of the regulatory statuses.** The reform
          names *déposée*, *rejetée*, *refusée* and *encaissée*, but the last
          two arrive from the buyer and from the agency's own books rather than
          from an API call. These three describe only what this application
          knows the moment it stops talking to the platform, which is the only
          thing an outbound attempt can honestly record.
        - :attr:`FAILED` is not terminal. A platform that was unreachable is a
          platform that will be reachable, and the money is settled either way —
          a failed transmission must never be readable as a failed payment.
    """

    PENDING = "pending"
    SENT = "sent"
    FAILED = "failed"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every transmission status.

        Returns:
            Tuple[str, ...]: ``("pending", "sent", "failed")``.
        """
        return tuple(status.value for status in cls)


@unique
class InterventionStatus(StrEnum):
    """Enumeration for the lifecycle status of a scheduled intervention.

    Attributes:
        PLANNED (str): Produced by the planning computation, not yet confirmed.
        CONFIRMED (str): Acknowledged by the assigned Home Care Assistant.
        COMPLETED (str): Delivered.
        CANCELLED (str): Called off; it no longer occupies the HCA's day.
    """

    PLANNED = "planned"
    CONFIRMED = "confirmed"
    COMPLETED = "completed"
    CANCELLED = "cancelled"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every intervention-status value.

        Returns:
            Tuple[str, ...]: The five supported statuses.
        """
        return tuple(status.value for status in cls)


@unique
class AvailabilityKind(StrEnum):
    """Enumeration for the reason a Home Care Assistant is unavailable.

    Attributes:
        HOLIDAY (str): Paid annual leave.
        DAY_OFF (str): A non-working day in the HCA's week.
        SICK_LEAVE (str): Medical leave.
        TRAINING (str): Attending a training session.
        UNAVAILABLE (str): Unavailable for any other reason.

    Notes:
        Every kind blocks scheduling identically; the distinction is recorded
        for reporting, not for the solver, which only asks whether a slot
        exists for a given day.
    """

    HOLIDAY = "holiday"
    DAY_OFF = "day-off"
    SICK_LEAVE = "sick-leave"
    TRAINING = "training"
    UNAVAILABLE = "unavailable"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every availability-kind value.

        Returns:
            Tuple[str, ...]: The five supported kinds.
        """
        return tuple(kind.value for kind in cls)


@unique
class Weekday(StrEnum):
    """Enumeration for the days of the week.

    Attributes:
        MONDAY (str): Monday, ISO weekday 1.
        TUESDAY (str): Tuesday, ISO weekday 2.
        WEDNESDAY (str): Wednesday, ISO weekday 3.
        THURSDAY (str): Thursday, ISO weekday 4.
        FRIDAY (str): Friday, ISO weekday 5.
        SATURDAY (str): Saturday, ISO weekday 6.
        SUNDAY (str): Sunday, ISO weekday 7.
    """

    MONDAY = "monday"
    TUESDAY = "tuesday"
    WEDNESDAY = "wednesday"
    THURSDAY = "thursday"
    FRIDAY = "friday"
    SATURDAY = "saturday"
    SUNDAY = "sunday"

    def iso_weekday(self) -> int:
        """Return the ISO weekday number of this day.

        Returns:
            int: ``1`` for Monday through ``7`` for Sunday, matching
            :meth:`datetime.date.isoweekday`.
        """
        numbers = {
            Weekday.MONDAY: 1,
            Weekday.TUESDAY: 2,
            Weekday.WEDNESDAY: 3,
            Weekday.THURSDAY: 4,
            Weekday.FRIDAY: 5,
            Weekday.SATURDAY: 6,
            Weekday.SUNDAY: 7,
        }
        return numbers[self]

    @classmethod
    def from_iso_weekday(cls, iso_weekday: int) -> Weekday:
        """Return the weekday matching an ISO weekday number.

        Args:
            iso_weekday (int): The ISO weekday number, ``1`` (Monday) to ``7``
                (Sunday), as returned by :meth:`datetime.date.isoweekday`.

        Returns:
            Weekday: The matching weekday.

        Raises:
            MTInvalidWeekday: If ``iso_weekday`` is outside the ``1..7`` range.
        """
        members = tuple(cls)
        if not isinstance(iso_weekday, int) or not 1 <= iso_weekday <= len(members):
            raise MTInvalidWeekday(
                f"Invalid ISO weekday: {iso_weekday!r}. Must be an int in 1..7."
            )
        return members[iso_weekday - 1]

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every weekday value.

        Returns:
            Tuple[str, ...]: The seven weekday values, Monday first.
        """
        return tuple(day.value for day in cls)


@unique
class PlanningRunStatus(StrEnum):
    """Enumeration for the lifecycle status of a planning computation.

    Attributes:
        PENDING (str): Accepted and queued, not yet picked up.
        RUNNING (str): The solver is running.
        SUCCEEDED (str): The solver finished and the interventions were written.
        PARTIAL (str): A plan was written, but some work could not be fitted.
        FAILED (str): The run ended on an error; see the run's error message.

    Notes:
        - :attr:`PARTIAL` exists because a week that mostly works is worth
          having. The run used to fail outright the moment one visit could not
          be placed, which left the agency with the *previous* week's calendar
          and a wall of text — safe, but it meant one impossible visit withheld
          eighty-nine perfectly good ones.
        - It is deliberately **not** ``SUCCEEDED``. A calendar missing three
          visits still looks like a calendar, and the visits quietly dropped are
          the ones that end with somebody waiting at their door — so the state
          has its own name, its own colour on the screen, and a report naming
         every quote involved.
    """

    PENDING = "pending"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    PARTIAL = "partial"
    FAILED = "failed"

    def is_terminal(self) -> bool:
        """Return whether no further status change can follow this one.

        Returns:
            bool: ``True`` for :attr:`SUCCEEDED`, :attr:`PARTIAL` and
            :attr:`FAILED`.

        Notes:
            Clients poll a run until this returns ``True``. A partial run is
            finished — the plan is written and nothing more will happen to it
            — so a client that kept polling would wait forever.
        """
        return self in (
            PlanningRunStatus.SUCCEEDED,
            PlanningRunStatus.PARTIAL,
            PlanningRunStatus.FAILED,
        )

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every planning-run-status value.

        Returns:
            Tuple[str, ...]: The five supported statuses.
        """
        return tuple(status.value for status in cls)


@unique
class ProbeStatus(StrEnum):
    """Enumeration for what an observability probe reports.

    Attributes:
        OK (str): The probe passed.
        UNAVAILABLE (str): The probe failed and the instance should be taken
            out of the load balancer.

    Notes:
        Shared by ``/health`` and ``/ready`` so an orchestrator reads one
        vocabulary from both. ``/health`` only ever reports :attr:`OK` — a
        liveness probe that fails gets the container restarted, and an API
        whose database blinked must not be.
    """

    OK = "ok"
    UNAVAILABLE = "unavailable"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every probe-status value.

        Returns:
            Tuple[str, ...]: ``("ok", "unavailable")``.
        """
        return tuple(status.value for status in cls)


@unique
class DatabaseStatus(StrEnum):
    """Enumeration for whether the database answered a readiness check.

    Attributes:
        REACHABLE (str): The database answered.
        UNREACHABLE (str): The database did not answer, or the check itself
            failed.

    Notes:
        Reported alongside :class:`ProbeStatus` so an operator reading a 503
        can tell "the store is down" from any other reason the instance is not
        ready, without opening the logs.
    """

    REACHABLE = "reachable"
    UNREACHABLE = "unreachable"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every database-status value.

        Returns:
            Tuple[str, ...]: ``("reachable", "unreachable")``.
        """
        return tuple(status.value for status in cls)


@unique
class UnplacedReason(StrEnum):
    """Why a piece of accepted work could not be scheduled.

    Attributes:
        OUT_OF_RADIUS: No assistant lives within the configured radius of it.
        NOT_A_WORKING_DAY: Nobody near enough works that day of the week.
        NO_ASSISTANT_AVAILABLE: Everybody near enough is absent that day.
        OUTSIDE_WORKING_DAY: Its window falls outside the working day.
        MISSING_CERTIFICATION: No field employee holds every qualification the
            work requires, unexpired on the day it happens.
        MISSING_SKILL: No field employee declares every skill the work
            requires, unexpired on the day it happens.
        CUSTOMER_CONFLICT: The customer has overlapping visits that cannot all
            fit without one starting before another ends.
        NO_FEASIBLE_SLOT: It could not be fitted around the rest of the plan —
            travel, lunch and the other visits together leave no room.

    Notes:
        - The reasons are ordered from most to least specific, and the checker
          reports the first that applies. "Out of radius" and "no feasible slot"
          are both true of a visit nobody can reach, but only the first tells a
          planner what to change.
        - :attr:`MISSING_CERTIFICATION` is tested **second**, ahead of anything
          geographical. A visit nobody is qualified for is also a visit nobody
          within the radius can take, and reporting the distance would send a
          manager to widen a radius that was never the problem. "Nobody here
          holds DEAES" names a hire, a training course or a wrong requirement —
          all things somebody can act on this afternoon.
        - :attr:`MISSING_SKILL` follows it, ahead of anything geographical for
          the same reason and *behind* the certification for a different one:
          the two are fixed by different people. A missing certification is a
          hire or a training course; a missing skill may be nothing more than
          somebody who can already do the work not having said so on their own
          screen. Reporting the certification first puts the harder problem in
          front of the manager, and a run blocked by both is blocked by the
          certification whatever the skills say.
        - :attr:`NOT_A_WORKING_DAY` is tested ahead of
          :attr:`NO_ASSISTANT_AVAILABLE`, and the two are genuinely different
          answers. "Nobody works Sundays" is a recruitment or a rota decision;
          "everybody is on leave that week" resolves itself on its own. Folding
          them together would report the second when the first is true, and send
          a manager looking through absence records for a day nobody had ever
          agreed to work.
        - What is *not* here: a window narrower than the service it holds has no
          member, because
          :class:`~models.planning.intervention.intervention_requirement.InterventionRequirement`
          refuses to build one. A reason that can never be reported would be a
          branch nothing exercises.
    """

    OUT_OF_RADIUS = "out-of-radius"
    NOT_A_WORKING_DAY = "not-a-working-day"
    NO_ASSISTANT_AVAILABLE = "no-assistant-available"
    OUTSIDE_WORKING_DAY = "outside-working-day"
    MISSING_CERTIFICATION = "missing-certification"
    MISSING_SKILL = "missing-skill"
    CUSTOMER_CONFLICT = "customer-conflict"
    NO_FEASIBLE_SLOT = "no-feasible-slot"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every unplaced-reason value.

        Returns:
            Tuple[str, ...]: The eight reasons work can go unplaced.
        """
        return tuple(reason.value for reason in cls)


@unique
class HcaApplicationStatus(StrEnum):
    """Where a self-submitted assistant registration has got to.

    Attributes:
        PENDING: Submitted, waiting for the chosen company to decide.
        APPROVED: Accepted; the assistant record and the account now exist.
        REJECTED: Declined; no account was ever created.

    Notes:
        Terminal states are kept rather than deleted. An applicant who was
        declined and applies again should be recognisable as such, and a
        deleted row cannot be.
    """

    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every application-status value.

        Returns:
            Tuple[str, ...]: ``("pending", "approved", "rejected")``.
        """
        return tuple(status.value for status in cls)

    def is_terminal(self) -> bool:
        """Return whether the application has been decided.

        Returns:
            bool: ``True`` for approved and rejected.
        """
        return self in (HcaApplicationStatus.APPROVED, HcaApplicationStatus.REJECTED)  # noqa: E501


@unique
class AccountOrigin(StrEnum):
    """How an account came to exist.

    Attributes:
        SELF_REGISTERED: The assistant applied and a company approved them.
        CREATED_BY_STAFF: An administrator or manager created it and issued a
            temporary password.

    Notes:
        Recorded because the two paths carry different obligations. An account
        created by staff starts with a password its owner has never chosen, and
        must be made to choose one before it can do anything; a self-registered
        account chose its own at the point of applying.
    """

    SELF_REGISTERED = "self-registered"
    CREATED_BY_STAFF = "created-by-staff"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every account-origin value.

        Returns:
            Tuple[str, ...]: ``("self-registered", "created-by-staff")``.
        """
        return tuple(origin.value for origin in cls)


@unique
class NotificationKind(StrEnum):
    """Enumeration for what a notification is about.

    Attributes:
        QUOTE_SUBMITTED (str): An assistant sent a quote for validation.
        QUOTE_VALIDATED (str): A manager approved a submitted quote.
        QUOTE_REFUSED (str): A manager sent a submitted quote back.
        PLANNING_COMPLETED (str): A planning run finished and calendars moved.
        SKILL_ADDED (str): An assistant declared a new skill about themselves.
        BILLS_TO_VALIDATE (str): A billing run wrote bills nobody has approved
            yet, and no customer has been sent anything.

    Notes:
        - The kind is what a client keys its icon, colour and deep link off, so
          it is an enumeration rather than free text. A notification whose kind
          nothing recognises is one the interface cannot route the reader
          anywhere useful from.
        - :attr:`SKILL_ADDED` is the one kind raised by something a *subordinate*
          did rather than by the quote workflow or the solver. It exists because
          a skill is self-declared and immediately affects who the planner may
          assign: somebody adding one silently widens what they can be sent to,
          and a supervisor who never hears about it has no opportunity to
          challenge it before the next run acts on it.
        - :attr:`BILLS_TO_VALIDATE` is the one kind that reports **inaction
          required before anything leaves the building**. A billing run renders
          every invoice and then stops; until a manager approves them no
          customer is sent anything, so a run nobody hears about is a month
          quietly unbilled. It carries no identifier of its own, for the same
          reason the planning kind does not — the reader goes to the list.
    """

    QUOTE_SUBMITTED = "quote-submitted"
    QUOTE_VALIDATED = "quote-validated"
    QUOTE_REFUSED = "quote-refused"
    PLANNING_COMPLETED = "planning-completed"
    SKILL_ADDED = "skill-added"
    BILLS_TO_VALIDATE = "bills-to-validate"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every notification-kind value.

        Returns:
            Tuple[str, ...]: The six supported kinds.
        """
        return tuple(kind.value for kind in cls)

    def concerns_a_quote(self) -> bool:
        """Return whether the notification points at a quote.

        Returns:
            bool: ``True`` for the three quote-workflow kinds.

        Notes:
            - Used to decide whether ``quote_id`` is expected to be populated,
              which is what makes the notification clickable.
            - Written as membership of the quote kinds rather than as "not the
              planning one". It read that way while ``PLANNING_COMPLETED`` was
              the only exception, and adding :attr:`SKILL_ADDED` would have made
              a skill notification claim to point at a quote it has no
              identifier for — rendering it as a link and producing a dead one.
        """
        return self in (
            NotificationKind.QUOTE_SUBMITTED,
            NotificationKind.QUOTE_VALIDATED,
            NotificationKind.QUOTE_REFUSED,
        )


@unique
class WorkerRole(StrEnum):
    """Enumeration for what a worker process consumes.

    Attributes:
        PLANNING (str): Consumes ``planning-runs``, and solves.
        NOTIFICATIONS (str): Consumes ``quote-notifications``, and writes
            notifications and emails.
        BILLING (str): Consumes ``billing-runs``, and renders invoices.

    Notes:
        - **One image, three deployments.** The consumers are unlike each other
          in the way that matters to a scheduler: a solve is CPU-bound and pins
          its cores for a thirty-second budget, while a notification fan-out is
          I/O-bound and finishes in milliseconds. Sharing a process means the
          planning worker's replica count is also the notification worker's, and a
          manager waits half a minute to be told a quote needs looking at because
          the pod is mid-solve.
        - Split, each scales on its own queue depth, gets its own resources, and
          can be put on its own node pool.
        - :attr:`BILLING` is the third role the split was leaving room for, and it
          earns its own deployment on the same criterion. Generating bills is
          neither CPU-pinned like a solve nor millisecond-quick like a badge: it
          is I/O-bound but **long**, because a monthly close over three hundred
          customers is three hundred documents rendered and three hundred objects
          uploaded. On the notifications role that close would sit at the head of
          ``quote-notifications`` for minutes and every quote badge would queue
          behind it — the very failure the first split exists to prevent,
          reproduced one level over. On the planning role it would contend with
          the solve and inherit a replica count scaled on solve latency, when its
          own queue spikes once a month and is empty the rest of the time.
        - **No role owns the control plane.** ``company.created`` is consumed by
          *all* of them, on an exclusive queue each, because each has its own
          queues to declare when an agency is founded. It is deliberately not a
          role of its own: one process hearing the announcement would leave the
          others serving every agency but the new one.
    """

    PLANNING = "planning"
    NOTIFICATIONS = "notifications"
    BILLING = "billing"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every worker-role value.

        Returns:
            Tuple[str, ...]: The three supported roles.
        """
        return tuple(role.value for role in cls)


@unique
class EventRoutingKey(StrEnum):
    """Enumeration for the topics the agency publishes events under.

    Attributes:
        QUOTE_SUBMITTED (str): An assistant sent a quote for validation.
        QUOTE_VALIDATED (str): A manager approved a submitted quote.
        QUOTE_REFUSED (str): A manager sent a submitted quote back.
        PLANNING_RUN_REQUESTED (str): A planning computation was asked for.
        PLANNING_RUN_COMPLETED (str): A planning computation finished.
        COMPANY_CREATED (str): An agency was founded.
        SKILL_ADDED (str): An assistant declared a new skill about themselves.
        NOTIFICATION_CREATED (str): Notifications were written and their
            recipients may be holding an open event stream.
        BILLING_RUN_REQUESTED (str): A period was asked to be billed.
        BILLING_RUN_COMPLETED (str): The bills for a period have been written.
        BILL_ACCEPTED (str): A manager validated a bill, which is what sends it.

    Notes:
        - An enumeration rather than string literals scattered across the
          publisher and the consumers, because a routing key typed differently
          in two places does not fail — it binds a queue that never receives
          anything, which looks exactly like a quiet system.
        - **These are the event half of a routing key, never a whole one.**
          Every message is published under ``<value>.<company_id>``; see
          :meth:`scoped_to`. Nothing binds a bare value, so an agency's traffic
          cannot reach another agency's queue.
        - ``COMPANY_CREATED`` is scoped the same way, under the identifier of
          the agency it announces. That keeps the rule uniform — there is no
          "global" event to remember to treat differently — and a worker that
          wants every one of them binds ``company.created.*`` explicitly.
        - ``NOTIFICATION_CREATED`` runs the other way round from the rest: the
          worker publishes it and the **API** consumes it, on a queue of each
          instance's own. It is what turns a written row into a push, and it
          carries recipient identifiers rather than the notifications
          themselves — the reader fetches those over HTTP, from the same
          endpoint it would have used had the push never arrived.
        - ``BILL_ACCEPTED`` is a separate topic from ``BILLING_RUN_COMPLETED``
          rather than a status carried on it, because the two have different
          payloads and different consequences. A completed run tells the agency
          it has invoices to look at; an accepted bill puts one in a customer's
          inbox. Folding them together would mean a run's completion could
          post an invoice nobody had approved, which is the whole reason a bill
          is generated waiting for validation.
    """

    QUOTE_SUBMITTED = "quote.submitted"
    QUOTE_VALIDATED = "quote.validated"
    QUOTE_REFUSED = "quote.refused"
    PLANNING_RUN_REQUESTED = "planning.run.requested"
    PLANNING_RUN_COMPLETED = "planning.run.completed"
    COMPANY_CREATED = "company.created"
    SKILL_ADDED = "skill.added"
    NOTIFICATION_CREATED = "notification.created"
    BILLING_RUN_REQUESTED = "billing.run.requested"
    BILLING_RUN_COMPLETED = "billing.run.completed"
    BILL_ACCEPTED = "bill.accepted"
    BILL_PAID = "bill.paid"

    def scoped_to(self, company_id: str) -> str:
        """Return the routing key this event takes for one agency.

        Args:
            company_id (str): The agency the event belongs to.

        Returns:
            str: ``"<event>.<company_id>"``.

        Raises:
            MTRoutingKeyMissingCompany: If ``company_id`` is empty.

        Notes:
            - The identifier goes last so a binding can select an agency with a
              suffix — ``quote.submitted.<id>`` for one, ``quote.submitted.*``
              for all. Putting it first would make "every event for this agency"
              easy and "this event for every agency" impossible, and the worker
              needs the second one to notice a newly founded agency.
            - An empty identifier raises rather than producing ``"quote.submitted."``,
              which is a valid topic key that binds to nothing — the silent
              failure this enumeration exists to prevent, one level down.
        """
        if not company_id:
            raise MTRoutingKeyMissingCompany(
                f"Cannot scope {self.value!r} to an empty company identifier."
            )
        return f"{self.value}.{company_id}"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every routing key.

        Returns:
            Tuple[str, ...]: The eleven supported routing keys.
        """
        return tuple(key.value for key in cls)

    def is_quote_event(self) -> bool:
        """Return whether the key belongs to the quote workflow.

        Returns:
            bool: ``True`` for the three quote topics.
        """
        return self.value.startswith("quote.")
