from __future__ import annotations

# Standard library imports
from decimal import Decimal
from enum import StrEnum, unique
from typing import Tuple

# First-party imports
from models.exceptions.enum_exceptions import (
    MTInvalidWeekday,
    MTRoutingKeyMissingCompany,
)


@unique
class RegistrationStatus(StrEnum):
    """Enumeration for the registration status of a customer.

    Attributes:
        ACTIVE (str): The customer is registered and may be quoted and served.
        STOPPED (str): The customer has stopped the service; no new quote or
            intervention may be created for them.
    """

    ACTIVE = "active"
    STOPPED = "stopped"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every registration-status value.

        Returns:
            Tuple[str, ...]: ``("active", "stopped")``.
        """
        return tuple(status.value for status in cls)


@unique
class Language(StrEnum):
    """Enumeration for the language a document is written in.

    Attributes:
        FR (str): French.
        EN (str): English.

    Notes:
        - The same two codes the interface offers, so an account's stored
          preference and the language its screens are in are one value rather
          than two that can disagree.
        - French is the default everywhere, and deliberately: this is a French
          home-care agency, and a quote reaching a customer in English because
          nobody set a preference would be the wrong failure. It is a stored
          preference rather than an ``Accept-Language`` header because the
          documents are generated by the planning-completed webhook, which runs
          in the background with no browser attached to read a header from.
    """

    FR = "fr"
    EN = "en"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every language value.

        Returns:
            Tuple[str, ...]: ``("fr", "en")``.
        """
        return tuple(language.value for language in cls)


@unique
class ContractType(StrEnum):
    """Enumeration for the employment contract of a Home Care Assistant.

    Attributes:
        CDI (str): Permanent open-ended contract (contrat à durée indéterminée).
        CDD (str): Fixed-term contract (contrat à durée déterminée).
        INTERIM (str): Temporary agency contract.
        INTERNSHIP (str): Internship (stage).
    """

    CDI = "cdi"
    CDD = "cdd"
    INTERIM = "interim"
    INTERNSHIP = "internship"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every contract-type value.

        Returns:
            Tuple[str, ...]: The four supported contract types.
        """
        return tuple(contract.value for contract in cls)


@unique
class ServiceCategory(StrEnum):
    """Enumeration for the VAT category an intervention type falls under.

    Attributes:
        NECESSITY (str): Service delivered for a necessity reason, taxed at the
            reduced 5.5% VAT rate.
        COMFORT (str): Service delivered for a comfort reason, taxed at the
            standard 20% VAT rate.

    Notes:
        The category is carried by the intervention type rather than by the
        quote line: a given type of care is structurally one or the other. A
        type that would need both categories must be split into two types.
    """

    NECESSITY = "necessity"
    COMFORT = "comfort"

    def vat_rate(self) -> Decimal:
        """Return the VAT rate applicable to this category.

        Returns:
            Decimal: ``Decimal("0.055")`` for a necessity service, and
            ``Decimal("0.20")`` for a comfort service.

        Notes:
            The rate is a :class:`~decimal.Decimal` and never a float, so it
            composes with the rest of the pricing arithmetic without losing
            cents to binary floating-point representation.
        """
        rates = {
            ServiceCategory.NECESSITY: Decimal("0.055"),
            ServiceCategory.COMFORT: Decimal("0.20"),
        }
        return rates[self]

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every service-category value.

        Returns:
            Tuple[str, ...]: ``("necessity", "comfort")``.
        """
        return tuple(category.value for category in cls)


@unique
class UserRole(StrEnum):
    """Enumeration for the role granted to an authenticated account.

    Attributes:
        HCA (str): A Home Care Assistant. Declares their own availability and
            sees their own planning only.
        MANAGER (str): Sees every HCA planning, manages customers, quotes and
            the intervention-type catalog, and edits an HCA's contract type
            and certifications.
        ADMIN (str): Everything a manager can do, plus running the planning
            computation and promoting a user to manager.
    """

    HCA = "hca"
    MANAGER = "manager"
    ADMIN = "admin"

    def rank(self) -> int:
        """Return the numeric access rank of this role.

        Returns:
            int: The access rank; a higher rank unlocks strictly more.

        Notes:
            The ordering is shared by the whole stack so the API guards and any
            client agree on which role unlocks which feature. Rank comparison
            answers "at least a manager"; it must not be used for the checks
            that are specific to being an HCA (such as owning a planning),
            which compare the role by identity instead.
        """
        ranks = {UserRole.HCA: 0, UserRole.MANAGER: 1, UserRole.ADMIN: 2}
        return ranks[self]

    def has_at_least(self, minimum: UserRole) -> bool:
        """Return whether this role ranks at or above ``minimum``.

        Args:
            minimum (UserRole): The lowest role that satisfies the check.

        Returns:
            bool: ``True`` when this role's rank is greater than or equal to
            the rank of ``minimum``.
        """
        return self.rank() >= minimum.rank()

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every role value.

        Returns:
            Tuple[str, ...]: ``("hca", "manager", "admin")``.
        """
        return tuple(role.value for role in cls)


@unique
class QuoteStatus(StrEnum):
    """Enumeration for the lifecycle status of a quote.

    Attributes:
        DRAFT (str): Being composed; lines may still be added or removed.
        PENDING_VALIDATION (str): Submitted by an assistant and waiting for a
            manager to validate it.
        SENT (str): Sent to the customer and awaiting their answer.
        ACCEPTED (str): Accepted by the customer. Only accepted quotes feed the
            planning computation.
        REJECTED (str): Declined by the customer.
        EXPIRED (str): Its validity date passed before an answer was given.

    Notes:
        ``PENDING_VALIDATION`` sits between the draft and the commitment. An
        assistant knows what a customer needs but does not set the agency's
        prices, so a quote they write waits for a manager before its work is
        committed. It is deliberately a status rather than a flag: a quote is in
        exactly one place at a time, and a boolean beside the status would allow
        the nonsense of an accepted quote still awaiting validation.

        ``SENT`` is **no longer produced by any path**. Validation used to stop
        there, needing a second acceptance that nothing on any screen asked for,
        so a validated quote's work silently never reached a planning run; both
        approval paths now end at ``ACCEPTED``. The member is kept because rows
        stored in it before that change still exist, and the interface keeps its
        tab and its accept button for exactly them.
    """

    DRAFT = "draft"
    PENDING_VALIDATION = "pending-validation"
    SENT = "sent"
    ACCEPTED = "accepted"
    REJECTED = "rejected"
    EXPIRED = "expired"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every quote-status value.

        Returns:
            Tuple[str, ...]: The six supported statuses.
        """
        return tuple(status.value for status in cls)

    def is_editable(self) -> bool:
        """Return whether the lines may still be changed.

        Returns:
            bool: ``True`` only for a draft.

        Notes:
            A quote awaiting validation is frozen: a manager must decide on the
            figures they were shown, not on figures that moved underneath them
            while they read.
        """
        return self is QuoteStatus.DRAFT

    def is_awaiting_validation(self) -> bool:
        """Return whether a manager still owes this quote a decision.

        Returns:
            bool: ``True`` when the quote sits in the validation queue.
        """
        return self is QuoteStatus.PENDING_VALIDATION


@unique
class InterventionStatus(StrEnum):
    """Enumeration for the lifecycle status of a scheduled intervention.

    Attributes:
        PLANNED (str): Produced by the planning computation, not yet confirmed.
        CONFIRMED (str): Acknowledged by the assigned Home Care Assistant.
        COMPLETED (str): Delivered.
        CANCELLED (str): Called off; it no longer occupies the HCA's day.
    """

    PLANNED = "planned"
    CONFIRMED = "confirmed"
    COMPLETED = "completed"
    CANCELLED = "cancelled"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every intervention-status value.

        Returns:
            Tuple[str, ...]: The four supported statuses.
        """
        return tuple(status.value for status in cls)


@unique
class AvailabilityKind(StrEnum):
    """Enumeration for the reason a Home Care Assistant is unavailable.

    Attributes:
        HOLIDAY (str): Paid annual leave.
        DAY_OFF (str): A non-working day in the HCA's week.
        SICK_LEAVE (str): Medical leave.
        TRAINING (str): Attending a training session.
        UNAVAILABLE (str): Unavailable for any other reason.

    Notes:
        Every kind blocks scheduling identically; the distinction is recorded
        for reporting, not for the solver, which only asks whether a slot
        exists for a given day.
    """

    HOLIDAY = "holiday"
    DAY_OFF = "day-off"
    SICK_LEAVE = "sick-leave"
    TRAINING = "training"
    UNAVAILABLE = "unavailable"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every availability-kind value.

        Returns:
            Tuple[str, ...]: The five supported kinds.
        """
        return tuple(kind.value for kind in cls)


@unique
class Weekday(StrEnum):
    """Enumeration for the days of the week.

    Attributes:
        MONDAY (str): Monday, ISO weekday 1.
        TUESDAY (str): Tuesday, ISO weekday 2.
        WEDNESDAY (str): Wednesday, ISO weekday 3.
        THURSDAY (str): Thursday, ISO weekday 4.
        FRIDAY (str): Friday, ISO weekday 5.
        SATURDAY (str): Saturday, ISO weekday 6.
        SUNDAY (str): Sunday, ISO weekday 7.
    """

    MONDAY = "monday"
    TUESDAY = "tuesday"
    WEDNESDAY = "wednesday"
    THURSDAY = "thursday"
    FRIDAY = "friday"
    SATURDAY = "saturday"
    SUNDAY = "sunday"

    def iso_weekday(self) -> int:
        """Return the ISO weekday number of this day.

        Returns:
            int: ``1`` for Monday through ``7`` for Sunday, matching
            :meth:`datetime.date.isoweekday`.
        """
        numbers = {
            Weekday.MONDAY: 1,
            Weekday.TUESDAY: 2,
            Weekday.WEDNESDAY: 3,
            Weekday.THURSDAY: 4,
            Weekday.FRIDAY: 5,
            Weekday.SATURDAY: 6,
            Weekday.SUNDAY: 7,
        }
        return numbers[self]

    @classmethod
    def from_iso_weekday(cls, iso_weekday: int) -> Weekday:
        """Return the weekday matching an ISO weekday number.

        Args:
            iso_weekday (int): The ISO weekday number, ``1`` (Monday) to ``7``
                (Sunday), as returned by :meth:`datetime.date.isoweekday`.

        Returns:
            Weekday: The matching weekday.

        Raises:
            MTInvalidWeekday: If ``iso_weekday`` is outside the ``1..7`` range.
        """
        members = tuple(cls)
        if not isinstance(iso_weekday, int) or not 1 <= iso_weekday <= len(members):
            raise MTInvalidWeekday(
                f"Invalid ISO weekday: {iso_weekday!r}. Must be an int in 1..7."
            )
        return members[iso_weekday - 1]

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every weekday value.

        Returns:
            Tuple[str, ...]: The seven weekday values, Monday first.
        """
        return tuple(day.value for day in cls)


@unique
class PlanningRunStatus(StrEnum):
    """Enumeration for the lifecycle status of a planning computation.

    Attributes:
        PENDING (str): Accepted and queued, not yet picked up.
        RUNNING (str): The solver is running.
        SUCCEEDED (str): The solver finished and the interventions were written.
        FAILED (str): The run ended on an error; see the run's error message.
    """

    PENDING = "pending"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"

    def is_terminal(self) -> bool:
        """Return whether no further status change can follow this one.

        Returns:
            bool: ``True`` for :attr:`SUCCEEDED` and :attr:`FAILED`.

        Notes:
            Clients poll a run until this returns ``True``.
        """
        return self in (PlanningRunStatus.SUCCEEDED, PlanningRunStatus.FAILED)

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every planning-run-status value.

        Returns:
            Tuple[str, ...]: The four supported statuses.
        """
        return tuple(status.value for status in cls)


@unique
class ProbeStatus(StrEnum):
    """Enumeration for what an observability probe reports.

    Attributes:
        OK (str): The probe passed.
        UNAVAILABLE (str): The probe failed and the instance should be taken
            out of the load balancer.

    Notes:
        Shared by ``/health`` and ``/ready`` so an orchestrator reads one
        vocabulary from both. ``/health`` only ever reports :attr:`OK` — a
        liveness probe that fails gets the container restarted, and an API
        whose database blinked must not be.
    """

    OK = "ok"
    UNAVAILABLE = "unavailable"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every probe-status value.

        Returns:
            Tuple[str, ...]: ``("ok", "unavailable")``.
        """
        return tuple(status.value for status in cls)


@unique
class DatabaseStatus(StrEnum):
    """Enumeration for whether the database answered a readiness check.

    Attributes:
        REACHABLE (str): The database answered.
        UNREACHABLE (str): The database did not answer, or the check itself
            failed.

    Notes:
        Reported alongside :class:`ProbeStatus` so an operator reading a 503
        can tell "the store is down" from any other reason the instance is not
        ready, without opening the logs.
    """

    REACHABLE = "reachable"
    UNREACHABLE = "unreachable"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every database-status value.

        Returns:
            Tuple[str, ...]: ``("reachable", "unreachable")``.
        """
        return tuple(status.value for status in cls)


@unique
class UnplacedReason(StrEnum):
    """Why a piece of accepted work could not be scheduled.

    Attributes:
        OUT_OF_RADIUS: No assistant lives within the configured radius of it.
        NOT_A_WORKING_DAY: Nobody near enough works that day of the week.
        NO_ASSISTANT_AVAILABLE: Everybody near enough is absent that day.
        OUTSIDE_WORKING_DAY: Its window falls outside the working day.
        MISSING_CERTIFICATION: No field employee holds every qualification the
            work requires, unexpired on the day it happens.
        MISSING_SKILL: No field employee declares every skill the work
            requires, unexpired on the day it happens.
        CUSTOMER_CONFLICT: The customer has overlapping visits that cannot all
            fit without one starting before another ends.
        NO_FEASIBLE_SLOT: It could not be fitted around the rest of the plan —
            travel, lunch and the other visits together leave no room.

    Notes:
        - The reasons are ordered from most to least specific, and the checker
          reports the first that applies. "Out of radius" and "no feasible slot"
          are both true of a visit nobody can reach, but only the first tells a
          planner what to change.
        - :attr:`MISSING_CERTIFICATION` is tested **second**, ahead of anything
          geographical. A visit nobody is qualified for is also a visit nobody
          within the radius can take, and reporting the distance would send a
          manager to widen a radius that was never the problem. "Nobody here
          holds DEAES" names a hire, a training course or a wrong requirement —
          all things somebody can act on this afternoon.
        - :attr:`MISSING_SKILL` follows it, ahead of anything geographical for
          the same reason and *behind* the certification for a different one:
          the two are fixed by different people. A missing certification is a
          hire or a training course; a missing skill may be nothing more than
          somebody who can already do the work not having said so on their own
          screen. Reporting the certification first puts the harder problem in
          front of the manager, and a run blocked by both is blocked by the
          certification whatever the skills say.
        - :attr:`NOT_A_WORKING_DAY` is tested ahead of
          :attr:`NO_ASSISTANT_AVAILABLE`, and the two are genuinely different
          answers. "Nobody works Sundays" is a recruitment or a rota decision;
          "everybody is on leave that week" resolves itself on its own. Folding
          them together would report the second when the first is true, and send
          a manager looking through absence records for a day nobody had ever
          agreed to work.
        - What is *not* here: a window narrower than the service it holds has no
          member, because
          :class:`~models.planning.intervention.intervention_requirement.InterventionRequirement`
          refuses to build one. A reason that can never be reported would be a
          branch nothing exercises.
    """

    OUT_OF_RADIUS = "out-of-radius"
    NOT_A_WORKING_DAY = "not-a-working-day"
    NO_ASSISTANT_AVAILABLE = "no-assistant-available"
    OUTSIDE_WORKING_DAY = "outside-working-day"
    MISSING_CERTIFICATION = "missing-certification"
    MISSING_SKILL = "missing-skill"
    CUSTOMER_CONFLICT = "customer-conflict"
    NO_FEASIBLE_SLOT = "no-feasible-slot"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every unplaced-reason value.

        Returns:
            Tuple[str, ...]: The eight reasons work can go unplaced.
        """
        return tuple(reason.value for reason in cls)


@unique
class HcaApplicationStatus(StrEnum):
    """Where a self-submitted assistant registration has got to.

    Attributes:
        PENDING: Submitted, waiting for the chosen company to decide.
        APPROVED: Accepted; the assistant record and the account now exist.
        REJECTED: Declined; no account was ever created.

    Notes:
        Terminal states are kept rather than deleted. An applicant who was
        declined and applies again should be recognisable as such, and a
        deleted row cannot be.
    """

    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every application-status value.

        Returns:
            Tuple[str, ...]: ``("pending", "approved", "rejected")``.
        """
        return tuple(status.value for status in cls)

    def is_terminal(self) -> bool:
        """Return whether the application has been decided.

        Returns:
            bool: ``True`` for approved and rejected.
        """
        return self in (HcaApplicationStatus.APPROVED, HcaApplicationStatus.REJECTED)


@unique
class AccountOrigin(StrEnum):
    """How an account came to exist.

    Attributes:
        SELF_REGISTERED: The assistant applied and a company approved them.
        CREATED_BY_STAFF: An administrator or manager created it and issued a
            temporary password.

    Notes:
        Recorded because the two paths carry different obligations. An account
        created by staff starts with a password its owner has never chosen, and
        must be made to choose one before it can do anything; a self-registered
        account chose its own at the point of applying.
    """

    SELF_REGISTERED = "self-registered"
    CREATED_BY_STAFF = "created-by-staff"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every account-origin value.

        Returns:
            Tuple[str, ...]: ``("self-registered", "created-by-staff")``.
        """
        return tuple(origin.value for origin in cls)


@unique
class NotificationKind(StrEnum):
    """Enumeration for what a notification is about.

    Attributes:
        QUOTE_SUBMITTED (str): An assistant sent a quote for validation.
        QUOTE_VALIDATED (str): A manager approved a submitted quote.
        QUOTE_REFUSED (str): A manager sent a submitted quote back.
        PLANNING_COMPLETED (str): A planning run finished and calendars moved.
        SKILL_ADDED (str): An assistant declared a new skill about themselves.

    Notes:
        - The kind is what a client keys its icon, colour and deep link off, so
          it is an enumeration rather than free text. A notification whose kind
          nothing recognises is one the interface cannot route the reader
          anywhere useful from.
        - :attr:`SKILL_ADDED` is the one kind raised by something a *subordinate*
          did rather than by the quote workflow or the solver. It exists because
          a skill is self-declared and immediately affects who the planner may
          assign: somebody adding one silently widens what they can be sent to,
          and a supervisor who never hears about it has no opportunity to
          challenge it before the next run acts on it.
    """

    QUOTE_SUBMITTED = "quote-submitted"
    QUOTE_VALIDATED = "quote-validated"
    QUOTE_REFUSED = "quote-refused"
    PLANNING_COMPLETED = "planning-completed"
    SKILL_ADDED = "skill-added"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every notification-kind value.

        Returns:
            Tuple[str, ...]: The five supported kinds.
        """
        return tuple(kind.value for kind in cls)

    def concerns_a_quote(self) -> bool:
        """Return whether the notification points at a quote.

        Returns:
            bool: ``True`` for the three quote-workflow kinds.

        Notes:
            - Used to decide whether ``quote_id`` is expected to be populated,
              which is what makes the notification clickable.
            - Written as membership of the quote kinds rather than as "not the
              planning one". It read that way while ``PLANNING_COMPLETED`` was
              the only exception, and adding :attr:`SKILL_ADDED` would have made
              a skill notification claim to point at a quote it has no
              identifier for — rendering it as a link and producing a dead one.
        """
        return self in (
            NotificationKind.QUOTE_SUBMITTED,
            NotificationKind.QUOTE_VALIDATED,
            NotificationKind.QUOTE_REFUSED,
        )


@unique
class WorkerRole(StrEnum):
    """Enumeration for what a worker process consumes.

    Attributes:
        PLANNING (str): Consumes ``planning-runs``, and solves.
        NOTIFICATIONS (str): Consumes ``quote-notifications``, and writes
            notifications and emails.

    Notes:
        - **One image, two deployments.** The two consumers are unlike each other
          in the way that matters to a scheduler: a solve is CPU-bound and pins
          its cores for a thirty-second budget, while a notification fan-out is
          I/O-bound and finishes in milliseconds. Sharing a process means the
          planning worker's replica count is also the notification worker's, and a
          manager waits half a minute to be told a quote needs looking at because
          the pod is mid-solve.
        - Split, each scales on its own queue depth, gets its own resources, and
          can be put on its own node pool — which is also what makes room for a
          third role later without disturbing either.
        - **Neither role owns the control plane.** ``company.created`` is consumed
          by *both*, on an exclusive queue each, because each has its own queues to
          declare when an agency is founded. It is deliberately not a third role:
          one process hearing the announcement would leave the other serving every
          agency but the new one.
    """

    PLANNING = "planning"
    NOTIFICATIONS = "notifications"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every worker-role value.

        Returns:
            Tuple[str, ...]: The two supported roles.
        """
        return tuple(role.value for role in cls)


@unique
class EventRoutingKey(StrEnum):
    """Enumeration for the topics the agency publishes events under.

    Attributes:
        QUOTE_SUBMITTED (str): An assistant sent a quote for validation.
        QUOTE_VALIDATED (str): A manager approved a submitted quote.
        QUOTE_REFUSED (str): A manager sent a submitted quote back.
        PLANNING_RUN_REQUESTED (str): A planning computation was asked for.
        PLANNING_RUN_COMPLETED (str): A planning computation finished.
        COMPANY_CREATED (str): An agency was founded.
        SKILL_ADDED (str): An assistant declared a new skill about themselves.
        NOTIFICATION_CREATED (str): Notifications were written and their
            recipients may be holding an open event stream.

    Notes:
        - An enumeration rather than string literals scattered across the
          publisher and the consumers, because a routing key typed differently
          in two places does not fail — it binds a queue that never receives
          anything, which looks exactly like a quiet system.
        - **These are the event half of a routing key, never a whole one.**
          Every message is published under ``<value>.<company_id>``; see
          :meth:`scoped_to`. Nothing binds a bare value, so an agency's traffic
          cannot reach another agency's queue.
        - ``COMPANY_CREATED`` is scoped the same way, under the identifier of
          the agency it announces. That keeps the rule uniform — there is no
          "global" event to remember to treat differently — and a worker that
          wants every one of them binds ``company.created.*`` explicitly.
        - ``NOTIFICATION_CREATED`` runs the other way round from the rest: the
          worker publishes it and the **API** consumes it, on a queue of each
          instance's own. It is what turns a written row into a push, and it
          carries recipient identifiers rather than the notifications
          themselves — the reader fetches those over HTTP, from the same
          endpoint it would have used had the push never arrived.
    """

    QUOTE_SUBMITTED = "quote.submitted"
    QUOTE_VALIDATED = "quote.validated"
    QUOTE_REFUSED = "quote.refused"
    PLANNING_RUN_REQUESTED = "planning.run.requested"
    PLANNING_RUN_COMPLETED = "planning.run.completed"
    COMPANY_CREATED = "company.created"
    SKILL_ADDED = "skill.added"
    NOTIFICATION_CREATED = "notification.created"

    def scoped_to(self, company_id: str) -> str:
        """Return the routing key this event takes for one agency.

        Args:
            company_id (str): The agency the event belongs to.

        Returns:
            str: ``"<event>.<company_id>"``.

        Raises:
            MTRoutingKeyMissingCompany: If ``company_id`` is empty.

        Notes:
            - The identifier goes last so a binding can select an agency with a
              suffix — ``quote.submitted.<id>`` for one, ``quote.submitted.*``
              for all. Putting it first would make "every event for this agency"
              easy and "this event for every agency" impossible, and the worker
              needs the second one to notice a newly founded agency.
            - An empty identifier raises rather than producing ``"quote.submitted."``,
              which is a valid topic key that binds to nothing — the silent
              failure this enumeration exists to prevent, one level down.
        """
        if not company_id:
            raise MTRoutingKeyMissingCompany(
                f"Cannot scope {self.value!r} to an empty company identifier."
            )
        return f"{self.value}.{company_id}"

    @classmethod
    def values(cls) -> Tuple[str, ...]:
        """Return every routing key.

        Returns:
            Tuple[str, ...]: The eight supported routing keys.
        """
        return tuple(key.value for key in cls)

    def is_quote_event(self) -> bool:
        """Return whether the key belongs to the quote workflow.

        Returns:
            bool: ``True`` for the three quote topics.
        """
        return self.value.startswith("quote.")
