from __future__ import annotations

# Standard library imports
from datetime import date, datetime
from typing import ClassVar, Optional, Union

# Third-party imports
from pydantic import BaseModel, Field, field_validator

# First-party imports
from models.people.hca.skill import Skill
from models.schemas.exceptions import (
    MTSkillCreateRequestInvalidCode,
    MTSkillCreateRequestInvalidDate,
    MTSkillCreateRequestInvalidIssuer,
    MTSkillCreateRequestInvalidName,
)


class SkillCreateRequest(BaseModel):
    """The payload an assistant declares one of their own skills with.

    Attributes:
        CODE_MAX_LENGTH (ClassVar[int]): Longest code accepted, matching the
            catalogue's own limit.
        name (str): Name of the skill.
        code (Optional[str]): The catalogue entry it instantiates, when it was
            picked from the catalogue rather than typed.
        issuer (Optional[str]): Who attested it, when there is anybody.
        obtained_on (Optional[date]): Date it was acquired.
        expires_on (Optional[date]): Date it lapses, or ``None``.

    Notes:
        - **There is no ``id`` and no ``hca_id``, and both absences are the
          permission.** The owning assistant comes from the credential and the
          identifier is generated by the store, so this payload cannot file a
          skill against a colleague and cannot overwrite an existing row by
          naming it. That is written as a shape rather than as a check, the
          same way ``AccountUpdateRequest`` carries no role.
        - It is a separate model from :class:`~models.people.hca.skill.Skill`
          rather than the domain model reused on the wire, for exactly that
          reason — ``Skill`` has an ``id``, and a route that accepted one would
          let a caller decide it.
        - :meth:`to_skill` is where the two meet, and it is the only place the
          conversion happens.
    """

    CODE_MAX_LENGTH: ClassVar[int] = 32

    name: str = Field(description="Name of the skill.")
    code: Optional[str] = Field(
        default=None,
        description="Catalogue code this skill instantiates, if any.",
    )
    issuer: Optional[str] = Field(
        default=None,
        description="Who attested the skill.",
    )
    obtained_on: Optional[date] = Field(
        default=None,
        description="Date the skill was acquired.",
    )
    expires_on: Optional[date] = Field(
        default=None,
        description="Date the skill lapses, or None if it does not.",
    )

    @field_validator("name", mode="before")
    def validate_name(cls, value: Optional[str]) -> str:
        """Validates that ``name`` is a non-empty string.

        Args:
            value (Optional[str]): Raw ``name`` value.

        Returns:
            str: The stripped skill name.

        Raises:
            MTSkillCreateRequestInvalidName: If ``value`` is not a string, or
                is empty once stripped.
        """
        if not isinstance(value, str) or not value.strip():
            raise MTSkillCreateRequestInvalidName(
                f"Invalid name: {value!r}. Must be a non-empty string."
            )
        return value.strip()

    @field_validator("code", mode="before")
    def validate_code(cls, value: Optional[str]) -> Optional[str]:
        """Validates that ``code`` is ``None`` or a catalogue key.

        Args:
            value (Optional[str]): Raw ``code`` value.

        Returns:
            Optional[str]: The upper-cased code, or ``None`` for a free-text
            skill.

        Raises:
            MTSkillCreateRequestInvalidCode: If ``value`` is neither ``None``
                nor a string of unaccented letters, digits, hyphens or
                underscores within :attr:`CODE_MAX_LENGTH`.

        Notes:
            A blank string reads as "not from the catalogue" rather than being
            rejected: the form offers a select that may be left empty, and
            refusing that would stop somebody recording a skill the catalogue
            does not yet have a name for.
        """
        if value is None:
            return None
        if not isinstance(value, str):
            raise MTSkillCreateRequestInvalidCode(
                f"Invalid code: {value!r}. Must be a string or None."
            )
        normalized = value.strip().upper()
        if not normalized:
            return None
        if len(normalized) > cls.CODE_MAX_LENGTH:
            raise MTSkillCreateRequestInvalidCode(
                f"Invalid code: {value!r}. Must be at most "
                f"{cls.CODE_MAX_LENGTH} characters."
            )
        if not all(
            (character.isascii() and character.isalnum()) or character in "-_"
            for character in normalized
        ):
            raise MTSkillCreateRequestInvalidCode(
                f"Invalid code: {value!r}. Must hold only unaccented "
                f"letters, digits, hyphens or underscores."
            )
        return normalized

    @field_validator("issuer", mode="before")
    def validate_issuer(cls, value: Optional[str]) -> Optional[str]:
        """Validates that ``issuer`` is ``None`` or a non-empty string.

        Args:
            value (Optional[str]): Raw ``issuer`` value.

        Returns:
            Optional[str]: The stripped issuer name, or ``None``.

        Raises:
            MTSkillCreateRequestInvalidIssuer: If ``value`` is neither ``None``
                nor a non-empty string.
        """
        if value is None:
            return None
        if not isinstance(value, str) or not value.strip():
            raise MTSkillCreateRequestInvalidIssuer(
                f"Invalid issuer: {value!r}. Must be a non-empty string or None."
            )
        return value.strip()

    @field_validator("obtained_on", "expires_on", mode="before")
    def validate_day(
        cls, value: Union[str, date, datetime, None]
    ) -> Union[str, date, None]:
        """Validates that a date is a date, an ISO string or ``None``.

        Args:
            value (Union[str, date, datetime, None]): Raw date value.

        Returns:
            Union[str, date, None]: The value handed back for Pydantic to
            parse.

        Raises:
            MTSkillCreateRequestInvalidDate: If ``value`` is neither ``None``
                nor a date-like value.

        Notes:
            One validator for both dates. Whether the expiry precedes the
            acquisition is not checked here — it is a rule about the pair, and
            :meth:`~models.people.hca.skill.Skill.check_dates` already owns it.
            Repeating it would give one mistake two different messages
            depending on which door it came through.
        """
        if value is None:
            return None
        if isinstance(value, datetime):
            return value.date()
        if isinstance(value, (str, date)):
            return value
        raise MTSkillCreateRequestInvalidDate(
            f"Invalid date: {value!r}. "
            f"Must be a date, an ISO-8601 string, or None."
        )

    ############################
    # Publicly Exposed Methods #
    ############################

    def to_skill(self) -> Skill:
        """Build the skill this payload declares.

        Returns:
            Skill: The skill, with no identifier — the store generates one.

        Raises:
            MTSkillInvalidExpiresOn: If the expiry precedes the acquisition.

        Notes:
            The identifier is deliberately left unset rather than defaulted to
            anything. It is what a later delete addresses, and one chosen by a
            caller would be one a caller could collide with somebody else's.
        """
        return Skill(
            name=self.name,
            code=self.code,
            issuer=self.issuer,
            obtained_on=self.obtained_on,
            expires_on=self.expires_on,
        )
