"""Record the language each account reads, and its documents are written in.

Revision ID: 0015
Revises: 0014
Create Date: 2026-08-07

Notes:
    The interface has offered French and English since it existed, but the
    choice lived in the browser's ``localStorage`` and never reached the
    server. That was enough while the language only decided what was on screen.
    It stopped being enough once the quotes emailed to customers had to come
    out in it: those are generated by the planning-completed webhook, which
    runs in the background with no browser attached and no header to read.

    So the preference moves server-side. ``users.language`` holds it, the
    account screen writes it, and the webhook reads it from the account that
    requested the run.

    **The backfill is the load-bearing part.** The column arrives with a server
    default of ``'fr'`` which is then dropped, the same shape migrations 0012
    and 0013 use. Every account that existed before this column did was reading
    a French interface unless they had personally switched — and a browser
    preference is not something this migration can see. French is also what the
    agency, its contract types and its holidays are, so it is the safe reading
    rather than merely the common one.

    Dropping the default afterwards is deliberate: the value belongs to the
    application's model, and a database-side default is a second place for it
    to be decided.
"""

from __future__ import annotations

# Third-party imports
from alembic import op
import sqlalchemy as sa

revision = "0015"
down_revision = "0014"
branch_labels = None
depends_on = None

# Spelled out rather than imported from the Language enum: a migration has to
# keep meaning the same thing after somebody edits that class, and an import
# would make this revision's behaviour depend on the code it runs against
# rather than on the schema it was written for.
DEFAULT_LANGUAGE = "fr"


def upgrade() -> None:
    """Add the language column and backfill every existing account."""
    op.add_column(
        "users",
        sa.Column(
            "language",
            sa.String(length=8),
            nullable=False,
            server_default=sa.text(f"'{DEFAULT_LANGUAGE}'"),
        ),
    )
    with op.batch_alter_table("users") as batch:
        batch.alter_column(
            "language",
            existing_type=sa.String(length=8),
            server_default=None,
        )


def downgrade() -> None:
    """Drop the language column.

    Notes:
        This loses every stored preference, and there is nowhere to put them —
        no earlier column holds "this account reads English". The interface
        keeps working: it falls back to the browser's own ``localStorage``,
        which is where the choice lived before this revision. What goes back to
        being wrong is the emailed documents, which return to being French for
        everybody.
    """
    op.drop_column("users", "language")
